### ISSUE TITLE
Getting Issue on APIS

### ISSUE THREAD

**Issue by kumaranilgupta** [OpenConextApps/apis#67]
Hi,
I am very new to OAuth2 and Maven and hence i am trying to install APIS and while i am running command from command prompt getting below issues

[ERROR] Failed to execute goal org.apache.openjpa:openjpa-maven-plugin:2.2.0:enh
ance (enhancer) on project apis-authorization-server: Execution enhancer of goal
org.apache.openjpa:openjpa-maven-plugin:2.2.0:enhance failed: Plugin org.apache
.openjpa:openjpa-maven-plugin:2.2.0 or one of its dependencies could not be reso
lved: Could not transfer artifact org.slf4j:slf4j-api:jar:1.6.1 from/to central
(https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [re
po.maven.apache.org/199.27.79.215] failed: Connection timed out: connect -> [Hel
p 1]

Please guide me to fix the issue .

**Comment by kumaranilgupta** [comment]
When I run it from Eclipse I am getting below error.


org.springframework.beans.factory.BeanDefinitionStoreException: Failed to load bean class: org.surfnet.oaaas.config.SpringConfiguration; nested exception is java.io.FileNotFoundException: class path resource [apis.application.properties] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:291) ~[spring-context-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:225) ~[spring-context-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:630) ~[spring-context-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:461) ~[spring-context-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410) ~[spring-web-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306) ~[spring-web-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112) [spring-web-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:549) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50) [jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.doStart(Server.java:224) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50) [jetty-util-6.1.26.jar:6.1.26]
	at runjettyrun.Bootstrap.main(Bootstrap.java:97) [run-jetty-run-bootstrap.jar:na]
Caused by: java.io.FileNotFoundException: class path resource [apis.application.properties] cannot be opened because it does not exist

**Comment by gvanderploeg** [comment]
Which submodule are you trying to run?
What command do you issue?
Are you aware of the fact that the apis-authorization-server-war needs a property file on the classpath named `apis.application.properties', as stated in the readme?

    The authorization server which you have started up with the maven jetty plugin uses the apis.application.properties file in apis-authorization-server-war/src/test/resources.

**Comment by kumaranilgupta** [comment]
Hi ,
I had issue with heap memory and now apis install successfully from command prompt, Can you let me know how do i use it on eclipse though have already imported but while i try for install it fails and also how can i run 2 war and 1 jar simultaneously from eclipse any help highly appreciated

**Comment by gvanderploeg** [comment]
Can you please explain what the exact problems are? Eclipse supports simultaneous execution by default so that should be no problem.
By the way: the m2eclipse plugin (for proper maven support in Eclipse) lets you run any maven goal from within Eclipse. Using that, you could simultaneously start jetty:run on different modules.

**Comment by kumaranilgupta** [comment]
Let me give you the complete details which i have imported in eclipse attaching snapshots...

when i try to install same source code on same path from command prompt it install successfully but with the eclipse i am getting below error.
*******************************************************************************************************************************
Running org.surfnet.oaaas.repository.AccessTokenRepositoryTest
14:46:37.558 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Building JPA container EntityManagerFactory for persistence unit 'oaaas'
14:46:38.517 [main] WARN  openjpa.Runtime - An error occurred while registering a ClassTransformer with PersistenceUnitInfo: name 'oaaas', root URL [file:/C:/Users/surya/git/apis/apis-authorization-server/target/classes]. The error has been consumed. To see it, set your openjpa.Runtime log level to TRACE. Load-time class transformation will not be available.
14:46:38.522 [main] DEBUG o.h.v.i.e.r.DefaultTraversableResolver - Found javax.persistence.Persistence on classpath containing 'getPersistenceUtil'. Assuming JPA 2 environment. Trying to instantiate JPA aware TraversableResolver
14:46:38.522 [main] DEBUG o.h.v.i.e.r.DefaultTraversableResolver - Instantiated JPA aware TraversableResolver of type org.hibernate.validator.internal.engine.resolver.JPATraversableResolver.
14:46:38.522 [main] DEBUG o.h.v.i.xml.ValidationXmlParser - Trying to load META-INF/validation.xml for XML based Validator configuration.
14:46:38.522 [main] DEBUG o.h.v.i.xml.ValidationXmlParser - No META-INF/validation.xml found. Using annotation based configuration only.
14:46:38.523 [main] INFO  openjpa.Runtime - OpenJPA dynamically loaded a validation provider.
14:46:38.570 [main] INFO  openjpa.Runtime - Starting OpenJPA 2.2.0
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.879 sec <<< FAILURE!
org.surfnet.oaaas.repository.AccessTokenRepositoryTest  Time elapsed: 12.878 sec  <<< ERROR!
<openjpa-2.2.0-r422266:1244990 fatal general error> org.apache.openjpa.persistence.PersistenceException: Database lock acquisition failure: lockFile: org.hsqldb.persist.LockFile@583edbb3[file =C:\Users\surya\git\apis\apis-authorization-server\target\db.lck, exists=true, locked=false, valid=false, ] method: checkHeartbeat read: 2015-01-08 09:16:48 heartbeat - read: -8120 ms.
	at org.apache.openjpa.jdbc.sql.DBDictionaryFactory.newDBDictionary(DBDictionaryFactory.java:102)
	at org.apache.openjpa.jdbc.conf.JDBCConfigurationImpl.getDBDictionaryInstance(JDBCConfigurationImpl.java:603)
*******************************************************************************************************************************
![eclipsesetup](https://cloud.githubusercontent.com/assets/5285047/5660607/23dd7f96-9748-11e4-9e69-e9fee9c3e6f4.jpg)

**Comment by kumaranilgupta** [comment]
Hi Again,
I have several issues while i try to configure this project on eclipse, I have build error in apis-authorization-server

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.openjpa:openjpa-maven-plugin:2.2.0:enhance (execution: enhancer, phase: process-classes)	pom.xml	/apis-authorization-server	line 154	Maven Project Build Lifecycle Mapping Problem

When I imported the project have got below mudule structure
****************************************************
apis-authorization-server
apis-authorization-server-dist
apis-authorization-server-war
apis-example-client-app
apis-example-resource-server
apis-example-resource-server-war
apis-openconext-mock-war
apis-parent
apis-resource-server-library
apis-surfconext-authn
**************************************************

So while i  run from apis-authorization-server-war module :
mvn jetty:run

I am getting below error

17:07:37.662 [main] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticator' defined in class org.surfnet.oaaas.config.SpringConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.surfnet.oaaas.auth.AbstractAuthenticator org.surfnet.oaaas.config.SpringConfiguration.authenticator()] threw exception; nested exception is java.lang.RuntimeException: javax.servlet.ServletException: java.lang.RuntimeException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Illegal footer: -property-named-idpCertificate

Also suggest me how can run all these 3 command from eclipse.

cd apis-authorization-server-war
mvn jetty:run

cd apis-example-resource-server
java -jar target/apis-example-resource-server-1.3.6-SNAPSHOT.jar

cd apis-example-client-app
mvn jetty:run

**Comment by kumaranilgupta** [comment]
Hi ,

I have now configured apis on eclipse had maven version issue, Now I am very close to completing the setup while i run on jetty from eclipse getting below error please suggest for a fix....

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticator' defined in class org.surfnet.oaaas.config.SpringConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.surfnet.oaaas.auth.AbstractAuthenticator org.surfnet.oaaas.config.SpringConfiguration.authenticator()] threw exception; nested exception is java.lang.RuntimeException: javax.servlet.ServletException: java.lang.RuntimeException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Illegal footer: -property-named-idpCertificate
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:589) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1055) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:951) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]

**Comment by kumaranilgupta** [comment]
Hi ,

I have now configured apis on eclipse had maven version issue, Now I am very close to completing the setup while i run on jetty from eclipse getting below error please suggest for a fix....

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticator' defined in class org.surfnet.oaaas.config.SpringConfiguration: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public org.surfnet.oaaas.auth.AbstractAuthenticator org.surfnet.oaaas.config.SpringConfiguration.authenticator()] threw exception; nested exception is java.lang.RuntimeException: javax.servlet.ServletException: java.lang.RuntimeException: java.security.cert.CertificateException: Could not parse certificate: java.io.IOException: Illegal footer: -property-named-idpCertificate
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:589) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1055) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:951) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296) ~[spring-beans-3.2.7.RELEASE.jar:3.2.7.RELEASE]

**Comment by gvanderploeg** [comment]
Hi,

The error that occurs is caused by the surfconext-authn module. You probably do not need this module at all, it is useful only for using a SAML IdP for authentication.
What does your apis.application.properties define as the authenticator class?
This should be sufficient for a first setup:

    authenticatorClass=org.surfnet.oaaas.authentication.FormLoginAuthenticator

**Comment by kumaranilgupta** [comment]
Hi ,

I have ignored my previous issue and running successfuly but still have some doubts I have migrated into mysql, and I could see the table resourceowner is not getting created but when i logged using emma.blunt', 'cafebabe' it worked for me and all the other table have created only except resourceowner .
